<?xml version="1.0" encoding="utf-8"?><Database Class="DbFileSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.B_WEB_HARD" Member="DbFileSystemItem">
    <Type Name="DbFileSystemItem">
      <Column Name="ID" Member="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PARENT_ID" Member="ParentId" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="IS_FOLDER" Member="IsFolder" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Column Name="NAME" Member="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastWriteDate" Member="LastWriteTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="Binary(8000)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>