--- 
name: Ext JS 3.3.0 Source
platform_id: all
platform_version: all
distribution_file_uuid_string: openlogic-extjs-3.3.0-all-src-1
platform_vendor: all
description: Ext JS 3.3.0 Source
platform_arch: all
distribution_file_uuid: 85c3bbd9213d26e52845cc6f70e7bad0d18f3947c93e97670c05cef62de4f551
distribution_version: 1
distribution_flavor: ""
distribution_raw_file: 3.3.0/ext-3.3.0.zip
notify: "yes"
package_version: 3.3.0
package_id: extjs
release_date: "2011-06-30"
distribution_notes: ""
distribution_type: src
