//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebContent_Views_SettingsView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebContent_Views_SettingsView() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebContent_Views_SettingsView", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   개인설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00000 {
            get {
                return ResourceManager.GetString("CSTRESX00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개인정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00001 {
            get {
                return ResourceManager.GetString("CSTRESX00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개인 신상 정보를 관리합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00002 {
            get {
                return ResourceManager.GetString("CSTRESX00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹웨어 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00003 {
            get {
                return ResourceManager.GetString("CSTRESX00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹웨어 기준정보를 관리합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00004 {
            get {
                return ResourceManager.GetString("CSTRESX00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메일함 관리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00005 {
            get {
                return ResourceManager.GetString("CSTRESX00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메일함을 관리합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00006 {
            get {
                return ResourceManager.GetString("CSTRESX00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시판 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00007 {
            get {
                return ResourceManager.GetString("CSTRESX00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시판 설정을 관리합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00008 {
            get {
                return ResourceManager.GetString("CSTRESX00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서명/답장 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00009 {
            get {
                return ResourceManager.GetString("CSTRESX00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서명 및 답장 설정을 관리합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00010 {
            get {
                return ResourceManager.GetString("CSTRESX00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스팸 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00011 {
            get {
                return ResourceManager.GetString("CSTRESX00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스팸 메일에 관련된 설정을 관리합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00012 {
            get {
                return ResourceManager.GetString("CSTRESX00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수신 차단/해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00013 {
            get {
                return ResourceManager.GetString("CSTRESX00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수신 차단을 관리합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00014 {
            get {
                return ResourceManager.GetString("CSTRESX00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부 메일 가져오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00015 {
            get {
                return ResourceManager.GetString("CSTRESX00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부 메일 가져오기를 관리합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00016 {
            get {
                return ResourceManager.GetString("CSTRESX00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패밀리 싸이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00017 {
            get {
                return ResourceManager.GetString("CSTRESX00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패밀리 싸이트에 관한 설정을 관리합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00018 {
            get {
                return ResourceManager.GetString("CSTRESX00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00019 {
            get {
                return ResourceManager.GetString("CSTRESX00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사진과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00020 {
            get {
                return ResourceManager.GetString("CSTRESX00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사원증 사진과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00021 {
            get {
                return ResourceManager.GetString("CSTRESX00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사진 올리기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00022 {
            get {
                return ResourceManager.GetString("CSTRESX00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00023 {
            get {
                return ResourceManager.GetString("CSTRESX00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사진을 삭제합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00024 {
            get {
                return ResourceManager.GetString("CSTRESX00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름(한글/중문)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00025 {
            get {
                return ResourceManager.GetString("CSTRESX00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   협력업체의 경우 지정되어있지 않을수도 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00026 {
            get {
                return ResourceManager.GetString("CSTRESX00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름(영문)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00027 {
            get {
                return ResourceManager.GetString("CSTRESX00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영문 이름이 지정되어있지 않습니다. 영문이름을 지정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00028 {
            get {
                return ResourceManager.GetString("CSTRESX00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *협력업체의 경우 지정되어있지 않을수도 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00029 {
            get {
                return ResourceManager.GetString("CSTRESX00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름(한자/중문)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00030 {
            get {
                return ResourceManager.GetString("CSTRESX00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한자 이름이 지정되어있지 않습니다. 한자 이름을 지정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00031 {
            get {
                return ResourceManager.GetString("CSTRESX00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   협력업체의 경우 지정되어있지 않을수도 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00032 {
            get {
                return ResourceManager.GetString("CSTRESX00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름(닉네임)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00033 {
            get {
                return ResourceManager.GetString("CSTRESX00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닉네임이 설정되어있지 않습니다. 닉네임을 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00034 {
            get {
                return ResourceManager.GetString("CSTRESX00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *닉네임 미설정시 다른 그룹웨어 사용자에게는 이름이 표시됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00035 {
            get {
                return ResourceManager.GetString("CSTRESX00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한 줄 소개를 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00036 {
            get {
                return ResourceManager.GetString("CSTRESX00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *한 줄 소개로 개성있는 나를 표현해 보세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00037 {
            get {
                return ResourceManager.GetString("CSTRESX00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디(식별번호) - 유효일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00038 {
            get {
                return ResourceManager.GetString("CSTRESX00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부 인증 메일 주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00039 {
            get {
                return ResourceManager.GetString("CSTRESX00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부 인증메일이 설정되어있지 않습니다. 외부 인증메일을 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00040 {
            get {
                return ResourceManager.GetString("CSTRESX00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *외부 인증메일이란 비밀번호 분실시 설정된 메일주로소 임시 비밀번호가 발송됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00041 {
            get {
                return ResourceManager.GetString("CSTRESX00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 - 유효일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00042 {
            get {
                return ResourceManager.GetString("CSTRESX00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영문 소/대 특수문자 조합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00043 {
            get {
                return ResourceManager.GetString("CSTRESX00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *비밀번호를 다시 확인합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00044 {
            get {
                return ResourceManager.GetString("CSTRESX00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00045 {
            get {
                return ResourceManager.GetString("CSTRESX00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입사일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00046 {
            get {
                return ResourceManager.GetString("CSTRESX00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사내 내선 번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00047 {
            get {
                return ResourceManager.GetString("CSTRESX00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사내 내선 번호가 설정되어있지 않습니다. 내선번호를 지정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00048 {
            get {
                return ResourceManager.GetString("CSTRESX00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *사내 내선번호만 입력하시면 됩니다. 예를들어 0585 이면 585만 입력하시면 전체 전화번호가 설정됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00049 {
            get {
                return ResourceManager.GetString("CSTRESX00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   휴대폰 번호가 지정되어있지 않습니다. 휴대폰 번호를 지정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00050 {
            get {
                return ResourceManager.GetString("CSTRESX00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *휴대폰 번호가 변경되었으면 변경된 번호로 업데이트 하세요. 단 ERP 사용자 정보에는 자동으로 변경되지는 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00051 {
            get {
                return ResourceManager.GetString("CSTRESX00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   긴급연락망과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00052 {
            get {
                return ResourceManager.GetString("CSTRESX00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   긴급연락망을 지정하여부세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00053 {
            get {
                return ResourceManager.GetString("CSTRESX00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *긴급연락망은 정말 급한 업무적인 일로 연락이 가능한 번호여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00054 {
            get {
                return ResourceManager.GetString("CSTRESX00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00055 {
            get {
                return ResourceManager.GetString("CSTRESX00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조직 / 속성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00056 {
            get {
                return ResourceManager.GetString("CSTRESX00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소속 사업장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00057 {
            get {
                return ResourceManager.GetString("CSTRESX00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소속 공장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00058 {
            get {
                return ResourceManager.GetString("CSTRESX00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소속 부서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00059 {
            get {
                return ResourceManager.GetString("CSTRESX00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   직급과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00060 {
            get {
                return ResourceManager.GetString("CSTRESX00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 종류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00061 {
            get {
                return ResourceManager.GetString("CSTRESX00061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 타입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00062 {
            get {
                return ResourceManager.GetString("CSTRESX00062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 구분과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00063 {
            get {
                return ResourceManager.GetString("CSTRESX00063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경사항 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00064 {
            get {
                return ResourceManager.GetString("CSTRESX00064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경된 모든내용을 저장합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00065 {
            get {
                return ResourceManager.GetString("CSTRESX00065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00066 {
            get {
                return ResourceManager.GetString("CSTRESX00066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경사항을 취소합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00067 {
            get {
                return ResourceManager.GetString("CSTRESX00067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한줄소개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00068 {
            get {
                return ResourceManager.GetString("CSTRESX00068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정 메일 주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00069 {
            get {
                return ResourceManager.GetString("CSTRESX00069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   휴대폰번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00070 {
            get {
                return ResourceManager.GetString("CSTRESX00070", resourceCulture);
            }
        }
    }
}
