//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebContent_Views_BoardView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebContent_Views_BoardView() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebContent_Views_BoardView", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   게시판과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00001 {
            get {
                return ResourceManager.GetString("CSTRESX00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메뉴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00002 {
            get {
                return ResourceManager.GetString("CSTRESX00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메뉴를 표시 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00003 {
            get {
                return ResourceManager.GetString("CSTRESX00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색어를 2글자 이상 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00004 {
            get {
                return ResourceManager.GetString("CSTRESX00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00005 {
            get {
                return ResourceManager.GetString("CSTRESX00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시판에서 검색합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00006 {
            get {
                return ResourceManager.GetString("CSTRESX00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이전글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00007 {
            get {
                return ResourceManager.GetString("CSTRESX00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 게시글의 이전글을 확인합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00008 {
            get {
                return ResourceManager.GetString("CSTRESX00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00009 {
            get {
                return ResourceManager.GetString("CSTRESX00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 게시글의 다음글을 확인합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00010 {
            get {
                return ResourceManager.GetString("CSTRESX00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00011 {
            get {
                return ResourceManager.GetString("CSTRESX00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 게시글에 답을을 작성합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00012 {
            get {
                return ResourceManager.GetString("CSTRESX00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00013 {
            get {
                return ResourceManager.GetString("CSTRESX00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 게시글을 수정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00014 {
            get {
                return ResourceManager.GetString("CSTRESX00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00015 {
            get {
                return ResourceManager.GetString("CSTRESX00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 게시글을 저장합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00016 {
            get {
                return ResourceManager.GetString("CSTRESX00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   임시보관과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00017 {
            get {
                return ResourceManager.GetString("CSTRESX00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작성중인 게시글을 임시보관 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00018 {
            get {
                return ResourceManager.GetString("CSTRESX00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00019 {
            get {
                return ResourceManager.GetString("CSTRESX00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 모드를 취소 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00020 {
            get {
                return ResourceManager.GetString("CSTRESX00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00021 {
            get {
                return ResourceManager.GetString("CSTRESX00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글을 삭제합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00022 {
            get {
                return ResourceManager.GetString("CSTRESX00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00023 {
            get {
                return ResourceManager.GetString("CSTRESX00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시판 리스트로 되돌아 갑니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00024 {
            get {
                return ResourceManager.GetString("CSTRESX00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글쓰기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00025 {
            get {
                return ResourceManager.GetString("CSTRESX00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 게시판에 글을 작성합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00026 {
            get {
                return ResourceManager.GetString("CSTRESX00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시판 통합 번호를 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00027 {
            get {
                return ResourceManager.GetString("CSTRESX00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제목과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00028 {
            get {
                return ResourceManager.GetString("CSTRESX00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제목을 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00029 {
            get {
                return ResourceManager.GetString("CSTRESX00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작성자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00030 {
            get {
                return ResourceManager.GetString("CSTRESX00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글 작성자를 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00031 {
            get {
                return ResourceManager.GetString("CSTRESX00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작성일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00032 {
            get {
                return ResourceManager.GetString("CSTRESX00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글 작성일을 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00033 {
            get {
                return ResourceManager.GetString("CSTRESX00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00034 {
            get {
                return ResourceManager.GetString("CSTRESX00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글을 조회된 횟수를 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00035 {
            get {
                return ResourceManager.GetString("CSTRESX00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추천과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00036 {
            get {
                return ResourceManager.GetString("CSTRESX00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글 추천된 횟수를 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00037 {
            get {
                return ResourceManager.GetString("CSTRESX00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   카테고리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00038 {
            get {
                return ResourceManager.GetString("CSTRESX00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시판선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00039 {
            get {
                return ResourceManager.GetString("CSTRESX00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시판을 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00040 {
            get {
                return ResourceManager.GetString("CSTRESX00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00041 {
            get {
                return ResourceManager.GetString("CSTRESX00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시판 그룹을 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00042 {
            get {
                return ResourceManager.GetString("CSTRESX00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   말머리선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00043 {
            get {
                return ResourceManager.GetString("CSTRESX00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글 리스트에서 보여질 말머리를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00044 {
            get {
                return ResourceManager.GetString("CSTRESX00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공지사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00045 {
            get {
                return ResourceManager.GetString("CSTRESX00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공지사항 채크시 제일 게시판의 제일 위에 표시됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00046 {
            get {
                return ResourceManager.GetString("CSTRESX00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   까지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00047 {
            get {
                return ResourceManager.GetString("CSTRESX00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제목과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00048 {
            get {
                return ResourceManager.GetString("CSTRESX00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글 제목을 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00049 {
            get {
                return ResourceManager.GetString("CSTRESX00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00050 {
            get {
                return ResourceManager.GetString("CSTRESX00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00051 {
            get {
                return ResourceManager.GetString("CSTRESX00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 지정 색상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00052 {
            get {
                return ResourceManager.GetString("CSTRESX00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글 제목의 색상을 지정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00053 {
            get {
                return ResourceManager.GetString("CSTRESX00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   굵게과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00054 {
            get {
                return ResourceManager.GetString("CSTRESX00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시글 제목을 굵게 표시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00055 {
            get {
                return ResourceManager.GetString("CSTRESX00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일첨부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00056 {
            get {
                return ResourceManager.GetString("CSTRESX00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   첨부파일 리스트 패널을 표시 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00057 {
            get {
                return ResourceManager.GetString("CSTRESX00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웹하드에서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00058 {
            get {
                return ResourceManager.GetString("CSTRESX00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웹하드에서 가져옵니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00059 {
            get {
                return ResourceManager.GetString("CSTRESX00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00060 {
            get {
                return ResourceManager.GetString("CSTRESX00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   첨부된 파일을 삭제 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00061 {
            get {
                return ResourceManager.GetString("CSTRESX00061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   첨부된 파일이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00062 {
            get {
                return ResourceManager.GetString("CSTRESX00062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00063 {
            get {
                return ResourceManager.GetString("CSTRESX00063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00064 {
            get {
                return ResourceManager.GetString("CSTRESX00064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업로드된 파일명을 확인합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00065 {
            get {
                return ResourceManager.GetString("CSTRESX00065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00066 {
            get {
                return ResourceManager.GetString("CSTRESX00066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업로드된 파일 확장자를 확인합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00067 {
            get {
                return ResourceManager.GetString("CSTRESX00067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   용량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00068 {
            get {
                return ResourceManager.GetString("CSTRESX00068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업로드된 파일의 용량을 확인합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00069 {
            get {
                return ResourceManager.GetString("CSTRESX00069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   태그과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00070 {
            get {
                return ResourceManager.GetString("CSTRESX00070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   태그와 태그는 쉼표(,)로 구분하며, 최대 10개까지 입력가능합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00071 {
            get {
                return ResourceManager.GetString("CSTRESX00071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색에 사용될 단어를 위주로 사용하여 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00072 {
            get {
                return ResourceManager.GetString("CSTRESX00072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공개설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00073 {
            get {
                return ResourceManager.GetString("CSTRESX00073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체공개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00074 {
            get {
                return ResourceManager.GetString("CSTRESX00074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내부공개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00075 {
            get {
                return ResourceManager.GetString("CSTRESX00075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   같은사업부만과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00076 {
            get {
                return ResourceManager.GetString("CSTRESX00076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채크시 나와 같은 사업부 사용자만 열람가능하게 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00077 {
            get {
                return ResourceManager.GetString("CSTRESX00077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   같은공장만과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00078 {
            get {
                return ResourceManager.GetString("CSTRESX00078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채크시 나와 같은 공장 사용자만 열람가능하게 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00079 {
            get {
                return ResourceManager.GetString("CSTRESX00079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   같은부서만과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00080 {
            get {
                return ResourceManager.GetString("CSTRESX00080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채크시 나와 같은 부서의 사용자만 열람가능하게 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00081 {
            get {
                return ResourceManager.GetString("CSTRESX00081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현장공개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00082 {
            get {
                return ResourceManager.GetString("CSTRESX00082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채크시 현장계정그룹의 사용자들은 열람가능하게 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00083 {
            get {
                return ResourceManager.GetString("CSTRESX00083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내부협력사공개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00084 {
            get {
                return ResourceManager.GetString("CSTRESX00084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채크시 내부협력사 계정그룹의 사용자들은 열람가능하게 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00085 {
            get {
                return ResourceManager.GetString("CSTRESX00085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   고객사공개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00086 {
            get {
                return ResourceManager.GetString("CSTRESX00086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채크시 고객사 계정그룹의 사용자들은 열람가능하게 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00087 {
            get {
                return ResourceManager.GetString("CSTRESX00087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부협력사공개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00088 {
            get {
                return ResourceManager.GetString("CSTRESX00088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채크시 외부협력사 계정그룹의 사용자들은 열람가능하게 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00089 {
            get {
                return ResourceManager.GetString("CSTRESX00089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - 전체공개이면 그룹웨어에 로그인된 사용자는 모두 열람가능합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00090 {
            get {
                return ResourceManager.GetString("CSTRESX00090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - 디아이씨공개이면 협력사 또는 고객사권한으로 로그인한 사용자는 확인할수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00091 {
            get {
                return ResourceManager.GetString("CSTRESX00091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00092 {
            get {
                return ResourceManager.GetString("CSTRESX00092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색허용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00093 {
            get {
                return ResourceManager.GetString("CSTRESX00093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹웨어에서 검색되는것을 허용합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00094 {
            get {
                return ResourceManager.GetString("CSTRESX00094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글쓰기화면을 로딩중입니다. 잠시만 기다려 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00095 {
            get {
                return ResourceManager.GetString("CSTRESX00095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일을 서버에 업로드 중 서버 내부오류가 발생하여 업로드 할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00096 {
            get {
                return ResourceManager.GetString("CSTRESX00096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 파일을 찾을수 없어 업로드가 취소되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00097 {
            get {
                return ResourceManager.GetString("CSTRESX00097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대 첨부가능한 용량 6G 를 넘을수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00098 {
            get {
                return ResourceManager.GetString("CSTRESX00098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 확장자는 업로드 할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00099 {
            get {
                return ResourceManager.GetString("CSTRESX00099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   덧글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00100 {
            get {
                return ResourceManager.GetString("CSTRESX00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00101 {
            get {
                return ResourceManager.GetString("CSTRESX00101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00102 {
            get {
                return ResourceManager.GetString("CSTRESX00102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추천과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00103 {
            get {
                return ResourceManager.GetString("CSTRESX00103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인쇄과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00104 {
            get {
                return ResourceManager.GetString("CSTRESX00104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게시물을 인쇄합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00105 {
            get {
                return ResourceManager.GetString("CSTRESX00105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00106 {
            get {
                return ResourceManager.GetString("CSTRESX00106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글을 게시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00107 {
            get {
                return ResourceManager.GetString("CSTRESX00107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00108 {
            get {
                return ResourceManager.GetString("CSTRESX00108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글을 수정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00109 {
            get {
                return ResourceManager.GetString("CSTRESX00109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00110 {
            get {
                return ResourceManager.GetString("CSTRESX00110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글을 삭제합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00111 {
            get {
                return ResourceManager.GetString("CSTRESX00111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정 취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00112 {
            get {
                return ResourceManager.GetString("CSTRESX00112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글 수정을 취소합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00113 {
            get {
                return ResourceManager.GetString("CSTRESX00113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글 달기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00114 {
            get {
                return ResourceManager.GetString("CSTRESX00114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글을 게시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00115 {
            get {
                return ResourceManager.GetString("CSTRESX00115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   덧글 달기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00116 {
            get {
                return ResourceManager.GetString("CSTRESX00116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   덧글을 게시합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00117 {
            get {
                return ResourceManager.GetString("CSTRESX00117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공지사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00118 {
            get {
                return ResourceManager.GetString("CSTRESX00118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00119 {
            get {
                return ResourceManager.GetString("CSTRESX00119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   많이 본 게시글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00120 {
            get {
                return ResourceManager.GetString("CSTRESX00120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}개의 첨부파일이 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00121 {
            get {
                return ResourceManager.GetString("CSTRESX00121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}개의 덧글이 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00122 {
            get {
                return ResourceManager.GetString("CSTRESX00122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy년 MM월 dd일 HH시 mm분 ss초과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00123 {
            get {
                return ResourceManager.GetString("CSTRESX00123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}명 확인 하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00124 {
            get {
                return ResourceManager.GetString("CSTRESX00124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}명이 추천 하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00125 {
            get {
                return ResourceManager.GetString("CSTRESX00125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00126 {
            get {
                return ResourceManager.GetString("CSTRESX00126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 게시판과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00127 {
            get {
                return ResourceManager.GetString("CSTRESX00127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 게시판 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00128 {
            get {
                return ResourceManager.GetString("CSTRESX00128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   답글 취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00129 {
            get {
                return ResourceManager.GetString("CSTRESX00129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내 PC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00130 {
            get {
                return ResourceManager.GetString("CSTRESX00130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일반 첨부파일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00131 {
            get {
                return ResourceManager.GetString("CSTRESX00131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC로 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00132 {
            get {
                return ResourceManager.GetString("CSTRESX00132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00133 {
            get {
                return ResourceManager.GetString("CSTRESX00133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00134 {
            get {
                return ResourceManager.GetString("CSTRESX00134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00135 {
            get {
                return ResourceManager.GetString("CSTRESX00135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00136 {
            get {
                return ResourceManager.GetString("CSTRESX00136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00137 {
            get {
                return ResourceManager.GetString("CSTRESX00137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00138 {
            get {
                return ResourceManager.GetString("CSTRESX00138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00139 {
            get {
                return ResourceManager.GetString("CSTRESX00139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00140 {
            get {
                return ResourceManager.GetString("CSTRESX00140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00141 {
            get {
                return ResourceManager.GetString("CSTRESX00141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00142 {
            get {
                return ResourceManager.GetString("CSTRESX00142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00143 {
            get {
                return ResourceManager.GetString("CSTRESX00143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00144 {
            get {
                return ResourceManager.GetString("CSTRESX00144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00145 {
            get {
                return ResourceManager.GetString("CSTRESX00145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00146 {
            get {
                return ResourceManager.GetString("CSTRESX00146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00147 {
            get {
                return ResourceManager.GetString("CSTRESX00147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00148 {
            get {
                return ResourceManager.GetString("CSTRESX00148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00149 {
            get {
                return ResourceManager.GetString("CSTRESX00149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00150 {
            get {
                return ResourceManager.GetString("CSTRESX00150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00151 {
            get {
                return ResourceManager.GetString("CSTRESX00151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00152 {
            get {
                return ResourceManager.GetString("CSTRESX00152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00153 {
            get {
                return ResourceManager.GetString("CSTRESX00153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00154 {
            get {
                return ResourceManager.GetString("CSTRESX00154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00155 {
            get {
                return ResourceManager.GetString("CSTRESX00155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00156 {
            get {
                return ResourceManager.GetString("CSTRESX00156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00157 {
            get {
                return ResourceManager.GetString("CSTRESX00157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00158 {
            get {
                return ResourceManager.GetString("CSTRESX00158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00159 {
            get {
                return ResourceManager.GetString("CSTRESX00159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00160 {
            get {
                return ResourceManager.GetString("CSTRESX00160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00161 {
            get {
                return ResourceManager.GetString("CSTRESX00161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00162 {
            get {
                return ResourceManager.GetString("CSTRESX00162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00163 {
            get {
                return ResourceManager.GetString("CSTRESX00163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00164 {
            get {
                return ResourceManager.GetString("CSTRESX00164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00165 {
            get {
                return ResourceManager.GetString("CSTRESX00165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00166 {
            get {
                return ResourceManager.GetString("CSTRESX00166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00167 {
            get {
                return ResourceManager.GetString("CSTRESX00167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00168 {
            get {
                return ResourceManager.GetString("CSTRESX00168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00169 {
            get {
                return ResourceManager.GetString("CSTRESX00169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00170 {
            get {
                return ResourceManager.GetString("CSTRESX00170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00171 {
            get {
                return ResourceManager.GetString("CSTRESX00171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00172 {
            get {
                return ResourceManager.GetString("CSTRESX00172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00173 {
            get {
                return ResourceManager.GetString("CSTRESX00173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00174 {
            get {
                return ResourceManager.GetString("CSTRESX00174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00175 {
            get {
                return ResourceManager.GetString("CSTRESX00175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00176 {
            get {
                return ResourceManager.GetString("CSTRESX00176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00177 {
            get {
                return ResourceManager.GetString("CSTRESX00177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00178 {
            get {
                return ResourceManager.GetString("CSTRESX00178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00179 {
            get {
                return ResourceManager.GetString("CSTRESX00179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00180 {
            get {
                return ResourceManager.GetString("CSTRESX00180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00181 {
            get {
                return ResourceManager.GetString("CSTRESX00181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00182 {
            get {
                return ResourceManager.GetString("CSTRESX00182", resourceCulture);
            }
        }
    }
}
