//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebContent_Views_Modules_B0_B0000MA1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebContent_Views_Modules_B0_B0000MA1() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebContent_Views_Modules_B0_B0000MA1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   자동채번등록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00001 {
            get {
                return ResourceManager.GetString("CSTRESX00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채번유형과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00002 {
            get {
                return ResourceManager.GetString("CSTRESX00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용시작일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00003 {
            get {
                return ResourceManager.GetString("CSTRESX00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채번유형코드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00004 {
            get {
                return ResourceManager.GetString("CSTRESX00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채번유형명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00005 {
            get {
                return ResourceManager.GetString("CSTRESX00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용시작일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00006 {
            get {
                return ResourceManager.GetString("CSTRESX00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동/수동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00007 {
            get {
                return ResourceManager.GetString("CSTRESX00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   접두어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00008 {
            get {
                return ResourceManager.GetString("CSTRESX00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   날짜유형과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00009 {
            get {
                return ResourceManager.GetString("CSTRESX00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대길이과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00010 {
            get {
                return ResourceManager.GetString("CSTRESX00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채번증가수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00011 {
            get {
                return ResourceManager.GetString("CSTRESX00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용여부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00012 {
            get {
                return ResourceManager.GetString("CSTRESX00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   날짜정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00013 {
            get {
                return ResourceManager.GetString("CSTRESX00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시리얼번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00014 {
            get {
                return ResourceManager.GetString("CSTRESX00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최종자동채번번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00015 {
            get {
                return ResourceManager.GetString("CSTRESX00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채번 유형과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00016 {
            get {
                return ResourceManager.GetString("CSTRESX00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00017 {
            get {
                return ResourceManager.GetString("CSTRESX00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSTRESX00018 {
            get {
                return ResourceManager.GetString("CSTRESX00018", resourceCulture);
            }
        }
    }
}
