//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ::::::: 대일기배|유| 그룹웨어 :::::::과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유니코드 지원과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00000 {
            get {
                return ResourceManager.GetString("GCSTRESX00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미리보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00001 {
            get {
                return ResourceManager.GetString("GCSTRESX00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인쇄과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00002 {
            get {
                return ResourceManager.GetString("GCSTRESX00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00003 {
            get {
                return ResourceManager.GetString("GCSTRESX00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00004 {
            get {
                return ResourceManager.GetString("GCSTRESX00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00005 {
            get {
                return ResourceManager.GetString("GCSTRESX00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   팝업과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00006 {
            get {
                return ResourceManager.GetString("GCSTRESX00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00007 {
            get {
                return ResourceManager.GetString("GCSTRESX00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00008 {
            get {
                return ResourceManager.GetString("GCSTRESX00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00009 {
            get {
                return ResourceManager.GetString("GCSTRESX00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00010 {
            get {
                return ResourceManager.GetString("GCSTRESX00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00011 {
            get {
                return ResourceManager.GetString("GCSTRESX00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러오는중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00100 {
            get {
                return ResourceManager.GetString("GCSTRESX00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청 형식이 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00101 {
            get {
                return ResourceManager.GetString("GCSTRESX00101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잘못된 요청입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00102 {
            get {
                return ResourceManager.GetString("GCSTRESX00102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   페이지 전환중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00103 {
            get {
                return ResourceManager.GetString("GCSTRESX00103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 페이지는 인증된 사용자만 사용하도록 되어있지만 로그인된 객체가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00104 {
            get {
                return ResourceManager.GetString("GCSTRESX00104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 셋이 비어있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00105 {
            get {
                return ResourceManager.GetString("GCSTRESX00105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인 객체가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00106 {
            get {
                return ResourceManager.GetString("GCSTRESX00106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 지정 타입 &lt;T&gt;에 대하여 데이터를 파싱하지 못하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00107 {
            get {
                return ResourceManager.GetString("GCSTRESX00107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터베이스에 연결할수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00300 {
            get {
                return ResourceManager.GetString("GCSTRESX00300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 메세지가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00301 {
            get {
                return ResourceManager.GetString("GCSTRESX00301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복된 데이터가 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX00500 {
            get {
                return ResourceManager.GetString("GCSTRESX00500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   페이지를 불러오던중 오류가 발생하여 요청한 페이지 불러오기가 중단되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX10000 {
            get {
                return ResourceManager.GetString("GCSTRESX10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청이 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20000 {
            get {
                return ResourceManager.GetString("GCSTRESX20000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 메일 아이디 형식은 지원하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20001 {
            get {
                return ResourceManager.GetString("GCSTRESX20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 메일의 첨부파일 번호가 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20002 {
            get {
                return ResourceManager.GetString("GCSTRESX20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 메일을 서버에서 찾을수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20003 {
            get {
                return ResourceManager.GetString("GCSTRESX20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 메일을 형식화된 객체로 변환하던중 오류가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20004 {
            get {
                return ResourceManager.GetString("GCSTRESX20004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 메일의 첨부된 파일이 없습니다. 관리자에게 문의 하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20005 {
            get {
                return ResourceManager.GetString("GCSTRESX20005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 첨부파일을 찾을수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20006 {
            get {
                return ResourceManager.GetString("GCSTRESX20006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 메일의 파서를 찾을수 없습니다. 관리자에게 문의 하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20007 {
            get {
                return ResourceManager.GetString("GCSTRESX20007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 대용량 첨부파일이 존재하지 않습니다. 관리자에게 문의 하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20008 {
            get {
                return ResourceManager.GetString("GCSTRESX20008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대용량 첨부 자료를 불러오던중 타입 변환 오류가 발생하여 다운로드 할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20009 {
            get {
                return ResourceManager.GetString("GCSTRESX20009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대용량 첨부 사용자 계정을 찾을수 없습니다. 퇴사등의 이유로 메일 서버에서 삭제 처리되었을수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20010 {
            get {
                return ResourceManager.GetString("GCSTRESX20010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 대용량 첨부파일은 기간이 만료되어 서버에서 삭제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20011 {
            get {
                return ResourceManager.GetString("GCSTRESX20011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드 기간이 만료되어 다운로드 할수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20012 {
            get {
                return ResourceManager.GetString("GCSTRESX20012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청하신 게시물의 실제 첨부 경로를 추출하던중 경로설정에 문제가 발생하였습니다. 관리자에게 문의하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20013 {
            get {
                return ResourceManager.GetString("GCSTRESX20013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 게시물의 첨부파일이 존재하지 않습니다. 관리자에게 문의 하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20014 {
            get {
                return ResourceManager.GetString("GCSTRESX20014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 외({1}건).zip과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20015 {
            get {
                return ResourceManager.GetString("GCSTRESX20015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 형식이 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20016 {
            get {
                return ResourceManager.GetString("GCSTRESX20016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장에 실패하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCSTRESX20017 {
            get {
                return ResourceManager.GetString("GCSTRESX20017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글꼴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10000 {
            get {
                return ResourceManager.GetString("GCTRRESX10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가나다라과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10001 {
            get {
                return ResourceManager.GetString("GCTRRESX10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글자크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10002 {
            get {
                return ResourceManager.GetString("GCTRRESX10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가나다라마바사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10003 {
            get {
                return ResourceManager.GetString("GCTRRESX10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가나다라마과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10004 {
            get {
                return ResourceManager.GetString("GCTRRESX10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가나다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10005 {
            get {
                return ResourceManager.GetString("GCTRRESX10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   굵게[Ctrl+B]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10006 {
            get {
                return ResourceManager.GetString("GCTRRESX10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   밑줄[Ctrl+U]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10007 {
            get {
                return ResourceManager.GetString("GCTRRESX10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기울임꼴[Ctrl+I]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10008 {
            get {
                return ResourceManager.GetString("GCTRRESX10008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소선[Ctrl+D]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10009 {
            get {
                return ResourceManager.GetString("GCTRRESX10009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글자색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10010 {
            get {
                return ResourceManager.GetString("GCTRRESX10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   더보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10011 {
            get {
                return ResourceManager.GetString("GCTRRESX10011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최근 사용한 색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10012 {
            get {
                return ResourceManager.GetString("GCTRRESX10012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10013 {
            get {
                return ResourceManager.GetString("GCTRRESX10013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배경색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10014 {
            get {
                return ResourceManager.GetString("GCTRRESX10014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글자색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10015 {
            get {
                return ResourceManager.GetString("GCTRRESX10015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   윗첨자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10016 {
            get {
                return ResourceManager.GetString("GCTRRESX10016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아래첨자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10017 {
            get {
                return ResourceManager.GetString("GCTRRESX10017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   왼쪽정렬과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10018 {
            get {
                return ResourceManager.GetString("GCTRRESX10018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가운대정렬과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10019 {
            get {
                return ResourceManager.GetString("GCTRRESX10019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오른쪽정렬과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10020 {
            get {
                return ResourceManager.GetString("GCTRRESX10020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   양쪽정렬과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10021 {
            get {
                return ResourceManager.GetString("GCTRRESX10021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번호매기기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10022 {
            get {
                return ResourceManager.GetString("GCTRRESX10022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글머리기호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10023 {
            get {
                return ResourceManager.GetString("GCTRRESX10023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내어쓰기[Shift+Tab]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10024 {
            get {
                return ResourceManager.GetString("GCTRRESX10024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   들여쓰기[Tab]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10025 {
            get {
                return ResourceManager.GetString("GCTRRESX10025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   줄간격과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10026 {
            get {
                return ResourceManager.GetString("GCTRRESX10026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   직접 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10027 {
            get {
                return ResourceManager.GetString("GCTRRESX10027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   더하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10028 {
            get {
                return ResourceManager.GetString("GCTRRESX10028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   빼기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10029 {
            get {
                return ResourceManager.GetString("GCTRRESX10029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10030 {
            get {
                return ResourceManager.GetString("GCTRRESX10030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10031 {
            get {
                return ResourceManager.GetString("GCTRRESX10031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인용구과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10032 {
            get {
                return ResourceManager.GetString("GCTRRESX10032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인용구 스타일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10033 {
            get {
                return ResourceManager.GetString("GCTRRESX10033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10034 {
            get {
                return ResourceManager.GetString("GCTRRESX10034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   링크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10035 {
            get {
                return ResourceManager.GetString("GCTRRESX10035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10036 {
            get {
                return ResourceManager.GetString("GCTRRESX10036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10037 {
            get {
                return ResourceManager.GetString("GCTRRESX10037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   특수기호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10038 {
            get {
                return ResourceManager.GetString("GCTRRESX10038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일반기호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10039 {
            get {
                return ResourceManager.GetString("GCTRRESX10039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숫자와 단위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10040 {
            get {
                return ResourceManager.GetString("GCTRRESX10040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원,괄호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10041 {
            get {
                return ResourceManager.GetString("GCTRRESX10041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10042 {
            get {
                return ResourceManager.GetString("GCTRRESX10042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그리스,라틴어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10043 {
            get {
                return ResourceManager.GetString("GCTRRESX10043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일본어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10044 {
            get {
                return ResourceManager.GetString("GCTRRESX10044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 기호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10045 {
            get {
                return ResourceManager.GetString("GCTRRESX10045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10046 {
            get {
                return ResourceManager.GetString("GCTRRESX10046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10047 {
            get {
                return ResourceManager.GetString("GCTRRESX10047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10048 {
            get {
                return ResourceManager.GetString("GCTRRESX10048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   칸수 지정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10049 {
            get {
                return ResourceManager.GetString("GCTRRESX10049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10050 {
            get {
                return ResourceManager.GetString("GCTRRESX10050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1행추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10051 {
            get {
                return ResourceManager.GetString("GCTRRESX10051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1행삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10052 {
            get {
                return ResourceManager.GetString("GCTRRESX10052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10053 {
            get {
                return ResourceManager.GetString("GCTRRESX10053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1열추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10054 {
            get {
                return ResourceManager.GetString("GCTRRESX10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1열삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10055 {
            get {
                return ResourceManager.GetString("GCTRRESX10055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속성직접입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10056 {
            get {
                return ResourceManager.GetString("GCTRRESX10056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표스타일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10057 {
            get {
                return ResourceManager.GetString("GCTRRESX10057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테두리없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10058 {
            get {
                return ResourceManager.GetString("GCTRRESX10058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테두리스타일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10059 {
            get {
                return ResourceManager.GetString("GCTRRESX10059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테두리두께과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10060 {
            get {
                return ResourceManager.GetString("GCTRRESX10060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1px 더하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10061 {
            get {
                return ResourceManager.GetString("GCTRRESX10061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1px 빼기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10062 {
            get {
                return ResourceManager.GetString("GCTRRESX10062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테두리색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10063 {
            get {
                return ResourceManager.GetString("GCTRRESX10063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   색찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10064 {
            get {
                return ResourceManager.GetString("GCTRRESX10064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   셀 배경색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10065 {
            get {
                return ResourceManager.GetString("GCTRRESX10065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표스타일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10066 {
            get {
                return ResourceManager.GetString("GCTRRESX10066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스타일 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10067 {
            get {
                return ResourceManager.GetString("GCTRRESX10067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표스타일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10068 {
            get {
                return ResourceManager.GetString("GCTRRESX10068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10069 {
            get {
                return ResourceManager.GetString("GCTRRESX10069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10070 {
            get {
                return ResourceManager.GetString("GCTRRESX10070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾기/바꾸기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10071 {
            get {
                return ResourceManager.GetString("GCTRRESX10071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10072 {
            get {
                return ResourceManager.GetString("GCTRRESX10072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10073 {
            get {
                return ResourceManager.GetString("GCTRRESX10073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바꾸기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10074 {
            get {
                return ResourceManager.GetString("GCTRRESX10074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾을 단어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10075 {
            get {
                return ResourceManager.GetString("GCTRRESX10075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스마트에디터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10076 {
            get {
                return ResourceManager.GetString("GCTRRESX10076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10077 {
            get {
                return ResourceManager.GetString("GCTRRESX10077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾을 단어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10078 {
            get {
                return ResourceManager.GetString("GCTRRESX10078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바꿀 단어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10079 {
            get {
                return ResourceManager.GetString("GCTRRESX10079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10080 {
            get {
                return ResourceManager.GetString("GCTRRESX10080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바꾸기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10081 {
            get {
                return ResourceManager.GetString("GCTRRESX10081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모두 바꾸기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10082 {
            get {
                return ResourceManager.GetString("GCTRRESX10082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10083 {
            get {
                return ResourceManager.GetString("GCTRRESX10083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML 에디터 로드중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10084 {
            get {
                return ResourceManager.GetString("GCTRRESX10084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배경작업 진행중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10085 {
            get {
                return ResourceManager.GetString("GCTRRESX10085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 파일이 없습니다. 파일을 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10086 {
            get {
                return ResourceManager.GetString("GCTRRESX10086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [제목 없음]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10087 {
            get {
                return ResourceManager.GetString("GCTRRESX10087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10088 {
            get {
                return ResourceManager.GetString("GCTRRESX10088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기본 언어를 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10089 {
            get {
                return ResourceManager.GetString("GCTRRESX10089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한글과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10090 {
            get {
                return ResourceManager.GetString("GCTRRESX10090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10091 {
            get {
                return ResourceManager.GetString("GCTRRESX10091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중문과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10092 {
            get {
                return ResourceManager.GetString("GCTRRESX10092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESX10093 {
            get {
                return ResourceManager.GetString("GCTRRESX10093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나눔고딕과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONT1 {
            get {
                return ResourceManager.GetString("GCTRRESXFONT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나눔명조과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONT2 {
            get {
                return ResourceManager.GetString("GCTRRESXFONT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나눔고딕코딩과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONT3 {
            get {
                return ResourceManager.GetString("GCTRRESXFONT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나눔바른고딕과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONT4 {
            get {
                return ResourceManager.GetString("GCTRRESXFONT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나눔바른펜과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONT5 {
            get {
                return ResourceManager.GetString("GCTRRESXFONT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;나눔고딕&apos;,NanumGothic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONTFM1 {
            get {
                return ResourceManager.GetString("GCTRRESXFONTFM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;나눔명조&apos;,NanumMyeongjo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONTFM2 {
            get {
                return ResourceManager.GetString("GCTRRESXFONTFM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;나눔고딕코딩&apos;,NanumGothicCoding과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONTFM3 {
            get {
                return ResourceManager.GetString("GCTRRESXFONTFM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;나눔바른고딕&apos;,NanumBarunGothic,NanumBarunGothicOTF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONTFM4 {
            get {
                return ResourceManager.GetString("GCTRRESXFONTFM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;나눔바른펜&apos;,NanumBarunpen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GCTRRESXFONTFM5 {
            get {
                return ResourceManager.GetString("GCTRRESXFONTFM5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ::::::: 대일기배|유| 그룹웨어 :::::::과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QuickName {
            get {
                return ResourceManager.GetString("QuickName", resourceCulture);
            }
        }
    }
}
